### ISSUE TITLE
Analyse_SAR.OSLdata() should point to analyse_SAR.CWOSL()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#216]
Starting with a capital letter, `Analyse_SAR.OSLdata()` is named inconsistently. I suggest renaming it to `analyse_SAR.OSLdata()`, leaving a stub with the old name that calls the newly-named function and throws a warning.

**Comment by RLumSK** [comment]
@mcol We keep it as is for historical reasons, because we have a paper detailing the workflow with this function. However, we should deprecate it for 1.0.0 and defunct it with 1.1.0.

I suggest: 

* Adding "deprecated" with version 1.0.0 
* Pointing to `analyse_SAR.CWOSL()` instead
* Add a tutorial to r-luminescence.org replicating what we have in the paper with the new function. Perhaps @maggithefox can write this tutorial, because she is first author on the paper in QI.

I am open to other suggestions, though.
