### ISSUE TITLE
plot_RLum.Data.Spectrum() crashes if bin.cols is set too high

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#415]
These crash:
```R
data(ExampleData.XSYG, envir = environment())
suppressWarnings(plot_RLum.Data.Spectrum(
        TL.Spectrum,
        plot.type = "persp",
        ylim = c(0, 100),
        bin.cols = 3))
# Error in if (size.diff != 0) { : argument is of length zero

suppressWarnings(plot_RLum.Data.Spectrum(
        TL.Spectrum,
        plot.type = "persp",
        ylim = c(0, 100),
        bin.cols = 8))
# Error: [plot_RLum.Data.Spectrum()] Unknown plot type
```

The examples work if `bin.cols = 2`; also `bin.cols = 3` works if I set `ylim = c(0, 200)`.

**Comment by mcol** [comment]
These as well:
```R
plot_RLum.Data.Spectrum(
        TL.Spectrum,
        plot.type = "persp",
        xlim = c(0, 100),
        bin.rows = 1)
# Error in col[1:(length(x) - 1)] :
#   only 0's may be mixed with negative subscripts
# In addition: Warning messages:
# 1: In min(x) : no non-missing arguments to min; returning Inf
# 2: In max(x) : no non-missing arguments to max; returning -Inf
# 3: In min(x) : no non-missing arguments to min; returning Inf
# 4: In max(x) : no non-missing arguments to max; returning -Inf

plot_RLum.Data.Spectrum(
        TL.Spectrum,
        plot.type = "persp",
        xlim = c(0, 100),
        bin.rows = 2)
# Error in rowsum.default(m, group = groups) : incorrect length for 'group'
```

**Comment by RLumSK** [comment]
I think what happens is that at some point nothing can be binned anymore, I believe we should calculate a maximum number of possible bins and if the uses adds a higher number we reset to max with a warning.

**Comment by RLumSK** [comment]
Update: I've looked up the code, the internal function `.matrix_binning()` works correctly for the binning and does not fail. Worst case is that it returns a single row/single column matrix. However, there seems to be an issue with the column and row name reassignment. Course of action:

- The binning should always work; also the column/row name alteration, but it should be done in `.matrix_binning()`
- The `plot_RLum.Data.Spectrum()` function should, however, throw a warning and fall back to `single` when the binning produces a single column/row matrix because a couple of plots require at least two columns/rows.

**Comment by mcol** [comment]
Thanks, I'll look into `.matrix_binning()` now.
