### ISSUE TITLE
Return type function "analyse_IRSARRF_SRS.cpp"

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#48]
Why using `RcppExport SEXP` instead of `List` (or `Rcpp::List`), because the function returns a List? I think it's an artefact from older versions from `Rcpp` package and not necessary with the command in line 14. 
With `List analyse_IRSARRF_SRS(....) ` all works fine too and it's much clearer what is the return type of this function.

https://github.com/R-Lum/Luminescence/blob/master/src/analyse_IRSARRF_SRS.cpp#L15

**Comment by RLumSK** [comment]
Does it matter? Does it speed up the calculation? Anyway, I've tried the list and it returns an error during the compliation, because of the 'C-linkage'. No idea what it means, but since the code runs ... never change a running system. By the way: The way of implementation was taken from the Rcpp Vignette.
