### ISSUE TITLE
suspicious code in analyse_SAR.CWOSL() if log = "x" and the first x is 0

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#523]
This chunk of code is used when `log = "x"` but the x values start from 0:

https://github.com/R-Lum/Luminescence/blob/cdae3243fd9c9224ac17e00b0fcbd81ce458cd20/R/analyse_SAR.CWOSL.R#L988-L995

Is this correct? It seems strange that we are shifting the values in the first row rather than the values in the first column. I would have expected this instead, as this shifts only the x-values: 
```R
object@records[[OSL.Curves.ID.Lx[[x]]]]@data[, 1] <-
              object@records[[OSL.Curves.ID.Lx[[x]]]]@data[, 1] + x.vals[2] - x.vals[1]
```

Note that the current approach makes `data[1, 1] == data[2, 1]` which again seems odd to me.

**Comment by RLumSK** [comment]
That is OK and for visualisation purpose only. The reason is that our curves technically can never start at 0, however, some machines return the first channel as 0, which cannot be correct and it does not work in the log plot for obvious reasons. Making the number just super small screws with the log plot.
