### ISSUE TITLE
calc_Huntley2006(): natural/simulated curve is not plotted in negative space

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#551]
Originally reported by @SalOehl: The natural/simulated curve is not plotted in negative space, so you cannot directly tell where it extrapolates to.

![issue_551](https://github.com/user-attachments/assets/f259d36f-55ac-4684-802c-10fea43013c0)

The simulated curve is plotted here:
https://github.com/R-Lum/Luminescence/blob/924aea8a7d9591755203f21aa4b2607dd880b935/R/calc_Huntley2006.R#L868-L873
with the x-values given by `natdosetimeGray`, which is always defined only on the positive axis:
https://github.com/R-Lum/Luminescence/blob/924aea8a7d9591755203f21aa4b2607dd880b935/R/calc_Huntley2006.R#L575

**Comment by RLumSK** [comment]
@mco, @SalOehl. This is actually **not** a bug. I had looked into this before and concluded that it does n to make sense to extrapolate the simulated curve into the negative space. But perhaps I am overlooking something.

**Comment by RLumSK** [comment]
OK, then we do this to provide better graphical feedback to the user. @SalOehl is this in your interest?

**Comment by SalOehl** [comment]
HI both,

I like the idea of changing the color to read for the negative space. But it also makes sense if it is not visible, because you are right, it is not fitted but modelled.
I am happy either way, but I think its nice if you can see the curve.

I will be away from office from now to the new year, but I will check my emails once in a while.
Thanks a lot for all of your quick responses to this!

Have a good holiday and a happy new year!
Salome

From: Sebastian Kreutzer ***@***.***>
Date: Thursday, 19 December 2024 at 17:54
To: R-Lum/Luminescence ***@***.***>
Cc: Salome Oehler ***@***.***>, Mention ***@***.***>
Subject: Re: [R-Lum/Luminescence] calc_Huntley2006(): natural/simulated curve is not plotted in negative space (Issue #551)

OK, then we do this to provide better graphical feedback to the user. @SalOehl<https://github.com/SalOehl> is this in your interest?
