### ISSUE TITLE
Add-in to install the development version of the package broken on Windows?

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#90]
@tzerk Can you please double-check our add-in to install the development version of 'Luminescence'. I could not manage to install the package via the add-in it always returned an R execution error...

**Comment by tzerk** [comment]
@RLumSK I had a quick look into it and also see the R execution error when running the addin. Can you check setting `Interactive: true` in the `inst/rstudio/addins.dcf` file? Make sure to re-build the package and also re-start RStudio afterwards. I haven't really tested it thoroughly though, but I haven't seen the error since. That being said, I am running into another problem with downloading the repo from Github through `devtools::install_github()`, but this is another problem. But from what I can see the execution error is seemingly unrelated to the API implementation itself.

**Comment by RLumSK** [comment]
Thanks, now it works again (at least on my computer). @tzerk can you please double-check and if ok, close the issue.

**Comment by tzerk** [comment]
Works fine for me now too and no more errors! Closed.
